### ISSUE TITLE
npm run test fails on import

### ISSUE THREAD

**Issue by imsickofmaps** [nicksp/redux-webpack-es6-boilerplate#32]
running `npm run test` outputs:

``````
± npm run test

> picsa-core-web@0.0.1 test /Users/mikej/Documents/glcode/picsa-core-web
> mocha --compilers js:babel-core/register,css:./test/unit/cssNullCompiler.js --require ./test/unit/testHelper.js --recursive ./test/unit

/Users/mikej/Documents/glcode/picsa-core-web/test/unit/testHelper.js:1
(function (exports, require, module, __filename, __dirname) { import jq from 'jquery';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at loader (/Users/mikej/Documents/glcode/picsa-core-web/node_modules/babel-register/lib/node.js:146:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/mikej/Documents/glcode/picsa-core-web/node_modules/babel-register/lib/node.js:156:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at /Users/mikej/Documents/glcode/picsa-core-web/node_modules/mocha/bin/_mocha:310:3
    at Array.forEach (native)
    at Object.<anonymous> (/Users/mikej/Documents/glcode/picsa-core-web/node_modules/mocha/bin/_mocha:309:10)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/6.5.0/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! picsa-core-web@0.0.1 test: `mocha --compilers js:babel-core/register,css:./test/unit/cssNullCompiler.js --require ./test/unit/testHelper.js --recursive ./test/unit`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the picsa-core-web@0.0.1 test script 'mocha --compilers js:babel-core/register,css:./test/unit/cssNullCompiler.js --require ./test/unit/testHelper.js --recursive ./test/unit'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the picsa-core-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha --compilers js:babel-core/register,css:./test/unit/cssNullCompiler.js --require ./test/unit/testHelper.js --recursive ./test/unit
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs picsa-core-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls picsa-core-web
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mikej/Documents/glcode/picsa-core-web/npm-debug.log```
``````

**Comment by nicksp** [comment]
Hi @imsickofmaps 
Yeah that's how it is. I left test setup from the prev version, but as i said in README, i have to re-setup it to reflect latest changes.

So will close that issue for now.

**Comment by drtechniko** [comment]
Hey @nicksp I got exactly that error above. Are you still active on the project and planning to fix it soon? I want to use your stuff because it looks nicely done but I can't really create a project from your boilerplate that won't be able to run tests.

I'm new to JS so if you know why the error happens and could let me know I can try to fix it myself.

**Comment by drtechniko** [comment]
Actually I did a bit more research and I think I'm going to lean towards this project starter instead so no worries: https://github.com/react-boilerplate/react-boilerplate/tree/v3.4.0

**Comment by noru** [comment]
For those who still care, to fix this:

1. remove `{ module: false }` in `.babelrc`
2. Fix/Remove all ill paths in *Spec.js, testHelp.js and whatever your terminal complained about, like:
- '../../../src/js'  -> '../../../src/client/assets/javascript'
